---
# vars file for deploy_mysql

deploy_mysql_root_pass        : 12345678
deploy_mysql_project_src      : /etc/docker/mysql
deploy_mysql_mysql_client_ver : 8.0.39-0ubuntu0.22.04.1
deploy_mysql_image_version    : 8.0.39
deploy_PyMySQL_ver            : 1.1.1
deploy_sql_master_ip          : 10.10.5.101
deploy_mysql_db_name          : wordpress
deploy_mysql_db_user          : wordpress
deploy_mysql_db_password      : wordpress
