#!/bin/bash

# Объявление основных входных переменных
lock_file=/tmp/log_report_sender.lock
log_file="/var/log/access-4560-644067.log"
email="m.v.kudryashov@ya.ru"
timestamp_file="/tmp/log_report_sender_last_run_timestamp"
tmp_log_file=$"/tmp/log_report_sender_tmp_file"
tmp_log_file=$(mktemp)

# Проверка существования файла блокировки (защита от повторного запуска скрипта)
if [ -e $lock_file ]; then
    echo "Error. Script is already running."
    exit 1
fi

# Создание файла блокировки
touch $lock_file

# Получение временной метки последнего запуска скрипта (если не запускался ставится метка "час назад")
if [ -f $timestamp_file ]; then
    last_run=$(cat $timestamp_file)
else
    last_run=$(date -d '1 hour ago' +"%d/%b/%Y:%H:%M:%S")
fi

# Запись временной метки
echo $(date +"%d/%b/%Y:%H:%M:%S") > "$timestamp_file"

# Выборка логов, сгенерированных с момента последнего запуска (или за последний час, если запуска еще не было) и помещение их во временный файл 
awk -v since=$last_run -v until="$(date '+%d/%b/%Y:%H:%M:%S')" '$4 > "["since && $4 < "["until' $log_file > $tmp_log_file

# Получение из лога интересующих данных
ip_requests=$(awk '{print $1}' $tmp_log_file | sort | uniq -c | sort -nr | head -10)
url_requests=$(awk '{print $7}' $tmp_log_file | sort | uniq -c | sort -nr | head -10)
errors=$(grep -E ' 50[0-9] ' $tmp_log_file)
http_codes=$(awk '{print $9}' $tmp_log_file | sort | uniq -c | sort -nr)

# Формирование и отправка письма
echo -e "Обрабатываемый временной диапазон: с $last_run по $(date +"%d/%b/%Y:%H:%M:%S")\n\nТоп IP адресов:\n$ip_requests\n\nТоп URL:\n$url_requests\n\nОшибки:\n$errors\n\nКоды HTTP ответа:\n$http_codes" | mail -s "Log Analysis Report" "$email"

# Удаление файла блокировки
rm -f $lock_file

# Завершение скрипта с кодом 0
exit 0