---
# tasks file for deploy_barman

- name: install barman, postgres and tools for python
  ansible.builtin.apt:
    name:
      - barman
      - postgresql
      - python3-pexpect
      - python3-psycopg2
    state: present
    update_cache: true
  when: inventory_hostname == "barman"

- name: generate SSH key for user postgres
  ansible.builtin.user:
    name: postgres
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    force: no
  when: inventory_hostname == "db01"

- name: generate SSH key for barman
  ansible.builtin.user:
    name: barman
    uid: 994
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    force: no
  when: inventory_hostname == "barman"

- name: fetch all public ssh keys postgres
  ansible.builtin.shell: cat /var/lib/postgresql/.ssh/id_rsa.pub
  register: ssh_keys
  when: inventory_hostname == "db01"

- name: transfer public key to barman
  delegate_to: barman
  authorized_key:
    key: "{{ ssh_keys.stdout }}"
    comment: "{{inventory_hostname}}"
    user: barman
  when: inventory_hostname == "db01"

- name: fetch all public ssh keys barman
  ansible.builtin.shell: cat /var/lib/barman/.ssh/id_rsa.pub
  register: ssh_keys
  when: inventory_hostname == "barman"

- name: transfer public key to barman
  delegate_to: db01
  authorized_key:
    key: "{{ ssh_keys.stdout }}"
    comment: "{{inventory_hostname}}"
    user: postgres
  when: inventory_hostname == "barman"

- name: copy .pgpass
  ansible.builtin.template:
    src: .pgpass.j2
    dest: /var/lib/barman/.pgpass
    owner: barman
    group: barman
    mode: '0600'
  when: inventory_hostname == "barman"

- name: create replicator user
  become_user: postgres
  postgresql_user:
    name: "barman"
    password: "{{ deploy_postgres_barman_pass }}"
    role_attr_flags: SUPERUSER 
  when: inventory_hostname == "db01"

- name: copy barman.conf
  ansible.builtin.template:
    src: barman.conf.j2
    dest: /etc/barman.conf 
    owner: barman
    group: barman
    mode: '0755'
  when: inventory_hostname == "barman"

- name: copy db01.conf
  ansible.builtin.template:
    src: barman.db01.conf.j2
    dest: /etc/barman.d/db01.conf
    owner: barman
    group: barman
    mode: '0755'
  when: inventory_hostname == "barman"

- name: create log file for barman
  ansible.builtin.file:
    path: /var/log/barman.log
    owner: barman
    group: barman
    mode: '0644'
    state: touch
  when: inventory_hostname == "barman"

- name: restart_postgres
  service:
    name: postgresql
    state: restarted
  when: inventory_hostname == "db01"

- name: barman switch-wal db01
  become_user: barman
  ansible.builtin.shell: barman switch-wal db01
  when: inventory_hostname == "barman"

- name: barman cron
  become_user: barman
  ansible.builtin.shell: barman cron
  when: inventory_hostname == "barman"