---
- hosts: all
  become: true

  tasks:
    - name: install packages
      ansible.builtin.apt:
        name: 
          - traceroute
          - tcpdump 
          - net-tools
          - frr
          - frr-pythontools
        state: present

    - name: set up forwarding packages across routers
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present

    - name: copy "frr-daemons.conf" to "/etc/frr/daemons'
      ansible.builtin.copy:
        src: frr-daemons.conf
        dest: /etc/frr/daemons
        owner: root
        group: root
        mode: 0755
        
    - name: copy "router1-frr.conf" to "/etc/frr/frr.conf'
      ansible.builtin.copy:
        src: router1-frr.conf
        dest: /etc/frr/frr.conf
        owner: frr
        group: frr
        mode: 0640
      when: ansible_host == "10.10.5.101"

    - name: copy "router2-frr.conf" to "/etc/frr/frr.conf'
      ansible.builtin.copy:
        src: router2-frr.conf
        dest: /etc/frr/frr.conf
        owner: frr
        group: frr
        mode: 0640
      when: ansible_host == "10.10.5.102"

    - name: copy "router3-frr.conf" to "/etc/frr/frr.conf'
      ansible.builtin.copy:
        src: router3-frr.conf
        dest: /etc/frr/frr.conf
        owner: frr
        group: frr
        mode: 0640
      when: ansible_host == "10.10.5.103"

    - name: restart FRR
      ansible.builtin.service:
        name: frr
        state: restarted
        enabled: true