- hosts: client
  become: true

  tasks:

    - name: change /etc/hosts
      ansible.builtin.template:
        src: hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644

    - name: install packeges
      ansible.builtin.yum:
        name:
          - freeipa-client
        state: present
        update_cache: true

    - name: add host to ipa-server
      ansible.builtin.shell: echo -e "yes\nyes" | ipa-client-install --mkhomedir --domain=LOCAL.LAN --server=server.local.lan --no-ntp -p admin -w 12345678
