#!/bin/bash

# Author: Maxim Kudryashov (m.v.kudryashov@ya.ru)

printf "%-10s %-10s %-10s %-10s %s\n" "pid" "tty" "stat" "time" "command"                          # Печать заголовка как в "ps ax"
    for pid in $(echo cat /proc/[[:digit:]]*/ | grep -o -E '[0-9]+'); do                           # Цикл for для каждого процесса (числовой директории) в /proc/
        if [ -d "/proc/$pid" ]; then                                                               # Условие существования директории процесса
            tty=$(readlink "/proc/$pid/fd/0")                                                      # Получение значения терминала
            stat=$(cat "/proc/$pid/status" | grep State: | awk '{print $2}')                       # Получение значения статуса процесса
            utime=$(cat "/proc/$pid/stat" | awk '{print $14}')                                     # Получение значения времени пространства пользователя
            stime=$(cat "/proc/$pid/stat" | awk '{print $15}')                                     # Получение значения времени пространства ядра 
            cmd=$(cat "/proc/$pid/cmdline" | tr '\0' ' ' | sed 's/\0/ /')                          # Получение cmdline процесса
            if [ -z "$cmd" ]; then                                                                 # Условие, если cmdline у процесса пустой
                cmd=[$(cat "/proc/$pid/status" | grep Name: | awk '{print $2}')]                   # Получение вместо cmdline имя процесса из файла status
            fi                                                                                     # Завершение условия
            printf "%-10s %-10s %-10s %-10s %s\n" "$pid" "$tty" "$stat" "$utime:$stime" "$cmd"     # Печать полученных переменных согласно формату заголовка
        fi                                                                                         # Завершение условия
    done                                                                                           # Завершение цикла for