---
- hosts: site-to-site
  become: true

  tasks:
    - name: install packages
      ansible.builtin.apt:
        name: 
          - openvpn
          - iperf3
        state: present

    - name: copy static.key file to servers
      ansible.builtin.copy:
        src: static.key
        dest: /etc/openvpn/static.key
        owner: root
        group: root
        mode: '0600'

    - name: copy server1_tap.conf file to server1
      ansible.builtin.copy:
        src: server1_tap.conf
        dest: /etc/openvpn/server_tap.conf
        owner: root
        group: root
        mode: '0644'
      when: ansible_host == "10.10.5.101"

    - name: copy server2_tap.conf file to server2
      ansible.builtin.copy:
        src: server2_tap.conf
        dest: /etc/openvpn/server_tap.conf
        owner: root
        group: root
        mode: '0644'
      when: ansible_host == "10.10.5.102"

    - name: start openvpn service on servers
      ansible.builtin.service:
        name: openvpn@server_tap.service
        state: started
        enabled: true