---
- hosts: office1-server
  become: true

  tasks:

    - name: insert lines in Netplan config after a specific line
      ansible.builtin.blockinfile:
        path: /etc/netplan/50-cloud-init.yaml
        marker: "# {mark} ANSIBLE MANAGED BLOCK def - Netplan configuration"
        insertafter: '      - "192.168.2.130/26"'
        block: "{{ lookup('template', 'routes-def_office1-server.j2') }}"
      notify: apply Netplan

  handlers:
    - name: apply Netplan
      ansible.builtin.command: netplan apply