---
# tasks file for deploy_nfs

  - name: update repositories cache and install "nfs-kernel-server" package on server
    ansible.builtin.apt:
      name: nfs-kernel-server
      update_cache: yes
    when: nfs_role == "nfs-server"

  - name: update repositories cache and install "nfs-common" package on client
    ansible.builtin.apt:
      name: nfs-common
      update_cache: yes
    when: nfs_role == "nfs-client"

  - name: create a directory if it does not exist
    ansible.builtin.file:
      path: /srv/share/upload
      state: directory
      owner: nobody
      group: nogroup
      mode: '0777'
    when: nfs_role == "nfs-server"

  - name: copy a file "exports" to /etc/nginx/sites-available/default
    ansible.builtin.copy:
      src: exports
      dest: /etc/exports
      owner: root
      group: root
      mode: '0644'
    notify: exportsfs-r
    when: nfs_role == "nfs-server"

  - name: add mount to fstab
    ansible.builtin.shell: echo "10.10.5.107:/srv/share/ /mnt nfs vers=3 0 0" >> /etc/fstab
    when: nfs_role == "nfs-client"

  - name: mount
    ansible.builtin.shell: mount -a
    when: nfs_role == "nfs-client"
