---
- hosts: inet-router
  become: true

  tasks:

    - name: install packages
      ansible.builtin.apt:
        name: knockd
        state: present

    - name: copy a file "knockd.conf" to /etc/knockd.conf
      ansible.builtin.copy:
        src: knockd.conf
        dest: /etc/knockd.conf
        owner: root
        group: root
        mode: '0664'
      notify: restart knockd.service

  handlers:
    - name: restart knockd.service
      ansible.builtin.service:
        name: knockd.service
        state: restarted